import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import {
  AccessibilityIcon,
  ActivityLogIcon,
  AlignBaselineIcon,
  AlignBottomIcon,
  AlignCenterHorizontallyIcon,
  AlignCenterVerticallyIcon,
  AlignLeftIcon,
  AlignRightIcon,
  AlignTopIcon,
  AllSidesIcon,
  AngleIcon,
  ArchiveIcon,
  ArrowBottomLeftIcon,
  ArrowBottomRightIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowTopLeftIcon,
  ArrowTopRightIcon,
  ArrowUpIcon,
  AspectRatioIcon,
  AvatarIcon,
  BackpackIcon,
  BadgeIcon,
  BarChartIcon,
  BellIcon,
  BlendingModeIcon,
  BookmarkIcon,
  BookmarkFilledIcon,
  BorderAllIcon,
  BorderBottomIcon,
  BorderDashedIcon,
  BorderDottedIcon,
  BorderLeftIcon,
  BorderNoneIcon,
  BorderRightIcon,
  BorderSolidIcon,
  BorderSplitIcon,
  BorderStyleIcon,
  BorderTopIcon,
  BorderWidthIcon,
  BoxIcon,
  BoxModelIcon,
  ButtonIcon,
  CalendarIcon,
  CameraIcon,
  CardStackIcon,
  CardStackMinusIcon,
  CardStackPlusIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CaretRightIcon,
  CaretSortIcon,
  CaretUpIcon,
  ChatBubbleIcon,
  CheckIcon,
  CheckCircledIcon,
  CheckboxIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CircleIcon,
  CircleBackslashIcon,
  ClipboardIcon,
  ClipboardCopyIcon,
  ClockIcon,
  CodeIcon,
  CodeSandboxLogoIcon,
  ColorWheelIcon,
  ColumnSpacingIcon,
  ColumnsIcon,
  CommitIcon,
  Component1Icon,
  Component2Icon,
  ComponentBooleanIcon,
  ComponentInstanceIcon,
  ComponentNoneIcon,
  ComponentPlaceholderIcon,
  ContainerIcon,
  CookieIcon,
  CopyIcon,
  CornerBottomLeftIcon,
  CornerBottomRightIcon,
  CornerTopLeftIcon,
  CornerTopRightIcon,
  CornersIcon,
  CountdownTimerIcon,
  CounterClockwiseClockIcon,
  CropIcon,
  Cross1Icon,
  Cross2Icon,
  CrossCircledIcon,
  Crosshair1Icon,
  Crosshair2Icon,
  CrumpledPaperIcon,
  CubeIcon,
  CursorArrowIcon,
  CursorTextIcon,
  DashIcon,
  DashboardIcon,
  DesktopIcon,
  DimensionsIcon,
  DiscIcon,
  DiscordLogoIcon,
  DividerHorizontalIcon,
  DividerVerticalIcon,
  DotIcon,
  DotFilledIcon,
  DotsHorizontalIcon,
  DotsVerticalIcon,
  DoubleArrowDownIcon,
  DoubleArrowLeftIcon,
  DoubleArrowRightIcon,
  DoubleArrowUpIcon,
  DownloadIcon,
  DragHandleDots1Icon,
  DragHandleDots2Icon,
  DragHandleHorizontalIcon,
  DragHandleVerticalIcon,
  DrawingPinIcon,
  DrawingPinFilledIcon,
  DropdownMenuIcon,
  EnterIcon,
  EnterFullScreenIcon,
  EnvelopeClosedIcon,
  EnvelopeOpenIcon,
  EraserIcon,
  ExclamationTriangleIcon,
  ExitIcon,
  ExitFullScreenIcon,
  ExternalLinkIcon,
  EyeClosedIcon,
  EyeNoneIcon,
  EyeOpenIcon,
  FaceIcon,
  FigmaLogoIcon,
  FileIcon,
  FileMinusIcon,
  FilePlusIcon,
  FileTextIcon,
  FontBoldIcon,
  FontFamilyIcon,
  FontItalicIcon,
  FontRomanIcon,
  FontSizeIcon,
  FontStyleIcon,
  FrameIcon,
  FramerLogoIcon,
  GearIcon,
  GitHubLogoIcon,
  GlobeIcon,
  GridIcon,
  GroupIcon,
  Half1Icon,
  Half2Icon,
  HamburgerMenuIcon,
  HandIcon,
  HeadingIcon,
  HeartIcon,
  HeartFilledIcon,
  HeightIcon,
  HobbyKnifeIcon,
  HomeIcon,
  IconJarLogoIcon,
  IdCardIcon,
  ImageIcon,
  InfoCircledIcon,
  InputIcon,
  InstagramLogoIcon,
  KeyboardIcon,
  LapTimerIcon,
  LaptopIcon,
  LayersIcon,
  LayoutIcon,
  LetterCaseCapitalizeIcon,
  LetterCaseLowercaseIcon,
  LetterCaseToggleIcon,
  LetterCaseUppercaseIcon,
  LetterSpacingIcon,
  LightningBoltIcon,
  LineHeightIcon,
  Link1Icon,
  Link2Icon,
  LinkBreak1Icon,
  LinkBreak2Icon,
  LinkNone1Icon,
  LinkNone2Icon,
  LinkedInLogoIcon,
  ListBulletIcon,
  LockClosedIcon,
  LockOpen1Icon,
  LockOpen2Icon,
  LoopIcon,
  MagicWandIcon,
  MagnifyingGlassIcon,
  MarginIcon,
  MaskOffIcon,
  MaskOnIcon,
  MinusIcon,
  MinusCircledIcon,
  MixIcon,
  MixerHorizontalIcon,
  MixerVerticalIcon,
  MobileIcon,
  ModulzLogoIcon,
  MoonIcon,
  MoveIcon,
  NotionLogoIcon,
  OpacityIcon,
  OpenInNewWindowIcon,
  OverlineIcon,
  PaddingIcon,
  PaperPlaneIcon,
  PauseIcon,
  Pencil1Icon,
  Pencil2Icon,
  PersonIcon,
  PieChartIcon,
  PilcrowIcon,
  PinBottomIcon,
  PinLeftIcon,
  PinRightIcon,
  PinTopIcon,
  PlayIcon,
  PlusIcon,
  PlusCircledIcon,
  QuestionMarkIcon,
  QuestionMarkCircledIcon,
  QuoteIcon,
  RadiobuttonIcon,
  ReaderIcon,
  ReloadIcon,
  ResetIcon,
  ResumeIcon,
  RocketIcon,
  RotateCounterClockwiseIcon,
  RowSpacingIcon,
  RowsIcon,
  RulerHorizontalIcon,
  RulerSquareIcon,
  ScissorsIcon,
  SectionIcon,
  SewingPinIcon,
  SewingPinFilledIcon,
  ShadowIcon,
  ShadowInnerIcon,
  ShadowNoneIcon,
  ShadowOuterIcon,
  Share1Icon,
  Share2Icon,
  ShuffleIcon,
  SizeIcon,
  SketchLogoIcon,
  SlashIcon,
  SliderIcon,
  SpaceBetweenHorizontallyIcon,
  SpaceBetweenVerticallyIcon,
  SpaceEvenlyHorizontallyIcon,
  SpaceEvenlyVerticallyIcon,
  SpeakerLoudIcon,
  SpeakerModerateIcon,
  SpeakerOffIcon,
  SpeakerQuietIcon,
  SquareIcon,
  StackIcon,
  StarIcon,
  StarFilledIcon,
  StitchesLogoIcon,
  StopIcon,
  StopwatchIcon,
  StretchHorizontallyIcon,
  StretchVerticallyIcon,
  StrikethroughIcon,
  SunIcon,
  SwitchIcon,
  SymbolIcon,
  TableIcon,
  TargetIcon,
  TextIcon,
  TextAlignBottomIcon,
  TextAlignCenterIcon,
  TextAlignJustifyIcon,
  TextAlignLeftIcon,
  TextAlignMiddleIcon,
  TextAlignRightIcon,
  TextAlignTopIcon,
  TextNoneIcon,
  ThickArrowDownIcon,
  ThickArrowLeftIcon,
  ThickArrowRightIcon,
  ThickArrowUpIcon,
  TimerIcon,
  TokensIcon,
  TrackNextIcon,
  TrackPreviousIcon,
  TransformIcon,
  TransparencyGridIcon,
  TrashIcon,
  TriangleDownIcon,
  TriangleLeftIcon,
  TriangleRightIcon,
  TriangleUpIcon,
  TwitterLogoIcon,
  UnderlineIcon,
  UpdateIcon,
  UploadIcon,
  ValueIcon,
  ValueNoneIcon,
  VercelLogoIcon,
  VideoIcon,
  ViewGridIcon,
  ViewHorizontalIcon,
  ViewNoneIcon,
  ViewVerticalIcon,
  WidthIcon,
  ZoomInIcon,
  ZoomOutIcon,
} from "@radix-ui/react-icons";
import { Label } from "@radix-ui/react-label";

import {
  BoldIcon, BriefcaseIcon, FacebookIcon, ItalicIcon,
  PenIcon, Trash2Icon, AArrowUpIcon, AArrowDownIcon, ALargeSmallIcon,
  ArrowDownLeftIcon, ArrowDownRightIcon, AlarmCheckIcon, AlarmClockIcon,
  AlarmClockOffIcon, AlarmPlusIcon, AlarmSmokeIcon, MailWarningIcon,
  ArrowUpLeftIcon, ArrowUpRightIcon, ArrowUpDownIcon,
} from "lucide-react";
import { useState } from "react";

const icons = [
  {name: "Accessibility", component: AccessibilityIcon},
  {name: "ActivityLog", component: ActivityLogIcon},
  {name: "AlignBaseline", component: AlignBaselineIcon},
  {name: "AlignBottom", component: AlignBottomIcon},
  {name: "AlignCenterHorizontally", component: AlignCenterHorizontallyIcon},
  {name: "AlignCenterVertically", component: AlignCenterVerticallyIcon},
  {name: "AlignLeft", component: AlignLeftIcon},
  {name: "AlignRight", component: AlignRightIcon},
  {name: "AlignTop", component: AlignTopIcon},
  {name: "AllSides", component: AllSidesIcon},
  {name: "Angle", component: AngleIcon},
  {name: "Archive", component: ArchiveIcon},
  {name: "ArrowBottomLeft", component: ArrowBottomLeftIcon},
  {name: "ArrowBottomRight", component: ArrowBottomRightIcon},
  {name: "ArrowDown", component: ArrowDownIcon},
  {name: "ArrowLeft", component: ArrowLeftIcon},
  {name: "ArrowRight", component: ArrowRightIcon},
  {name: "ArrowTopLeft", component: ArrowTopLeftIcon},
  {name: "ArrowTopRight", component: ArrowTopRightIcon},
  {name: "ArrowUp", component: ArrowUpIcon},
  {name: "AspectRatio", component: AspectRatioIcon},
  {name: "Avatar", component: AvatarIcon},
  {name: "Backpack", component: BackpackIcon},
  {name: "Badge", component: BadgeIcon},
  {name: "BarChart", component: BarChartIcon},
  {name: "Bell", component: BellIcon},
  {name: "BlendingMode", component: BlendingModeIcon},
  {name: "Bookmark", component: BookmarkIcon},
  {name: "BookmarkFilled", component: BookmarkFilledIcon},
  {name: "BorderAll", component: BorderAllIcon},
  {name: "BorderBottom", component: BorderBottomIcon},
  {name: "BorderDashed", component: BorderDashedIcon},
  {name: "BorderDotted", component: BorderDottedIcon},
  {name: "BorderLeft", component: BorderLeftIcon},
  {name: "BorderNone", component: BorderNoneIcon},
  {name: "BorderRight", component: BorderRightIcon},
  {name: "BorderSolid", component: BorderSolidIcon},
  {name: "BorderSplit", component: BorderSplitIcon},
  {name: "BorderStyle", component: BorderStyleIcon},
  {name: "BorderTop", component: BorderTopIcon},
  {name: "BorderWidth", component: BorderWidthIcon},
  {name: "Box", component: BoxIcon},
  {name: "BoxModel", component: BoxModelIcon},
  {name: "Button", component: ButtonIcon},
  {name: "Calendar", component: CalendarIcon},
  {name: "Camera", component: CameraIcon},
  {name: "CardStack", component: CardStackIcon},
  {name: "CardStackMinus", component: CardStackMinusIcon},
  {name: "CardStackPlus", component: CardStackPlusIcon},
  {name: "CaretDown", component: CaretDownIcon},
  {name: "CaretLeft", component: CaretLeftIcon},
  {name: "CaretRight", component: CaretRightIcon},
  {name: "CaretSort", component: CaretSortIcon},
  {name: "CaretUp", component: CaretUpIcon},
  {name: "ChatBubble", component: ChatBubbleIcon},
  {name: "Check", component: CheckIcon},
  {name: "CheckCircled", component: CheckCircledIcon},
  {name: "Checkbox", component: CheckboxIcon},
  {name: "ChevronDown", component: ChevronDownIcon},
  {name: "ChevronLeft", component: ChevronLeftIcon},
  {name: "ChevronRight", component: ChevronRightIcon},
  {name: "ChevronUp", component: ChevronUpIcon},
  {name: "Circle", component: CircleIcon},
  {name: "CircleBackslash", component: CircleBackslashIcon},
  {name: "Clipboard", component: ClipboardIcon},
  {name: "ClipboardCopy", component: ClipboardCopyIcon},
  {name: "Clock", component: ClockIcon},
  {name: "Code", component: CodeIcon},
  {name: "CodeSandboxLogo", component: CodeSandboxLogoIcon},
  {name: "ColorWheel", component: ColorWheelIcon},
  {name: "ColumnSpacing", component: ColumnSpacingIcon},
  {name: "Columns", component: ColumnsIcon},
  {name: "Commit", component: CommitIcon},
  {name: "Component1", component: Component1Icon},
  {name: "Component2", component: Component2Icon},
  {name: "ComponentBoolean", component: ComponentBooleanIcon},
  {name: "ComponentInstance", component: ComponentInstanceIcon},
  {name: "ComponentNone", component: ComponentNoneIcon},
  {name: "ComponentPlaceholder", component: ComponentPlaceholderIcon},
  {name: "Container", component: ContainerIcon},
  {name: "Cookie", component: CookieIcon},
  {name: "Copy", component: CopyIcon},
  {name: "CornerBottomLeft", component: CornerBottomLeftIcon},
  {name: "CornerBottomRight", component: CornerBottomRightIcon},
  {name: "CornerTopLeft", component: CornerTopLeftIcon},
  {name: "CornerTopRight", component: CornerTopRightIcon},
  {name: "Corners", component: CornersIcon},
  {name: "CountdownTimer", component: CountdownTimerIcon},
  {name: "CounterClockwiseClock", component: CounterClockwiseClockIcon},
  {name: "Crop", component: CropIcon},
  {name: "Cross1", component: Cross1Icon},
  {name: "Cross2", component: Cross2Icon},
  {name: "CrossCircled", component: CrossCircledIcon},
  {name: "Crosshair1", component: Crosshair1Icon},
  {name: "Crosshair2", component: Crosshair2Icon},
  {name: "CrumpledPaper", component: CrumpledPaperIcon},
  {name: "Cube", component: CubeIcon},
  {name: "CursorArrow", component: CursorArrowIcon},
  {name: "CursorText", component: CursorTextIcon},
  {name: "Dash", component: DashIcon},
  {name: "Dashboard", component: DashboardIcon},
  {name: "Desktop", component: DesktopIcon},
  {name: "Dimensions", component: DimensionsIcon},
  {name: "Disc", component: DiscIcon},
  {name: "DiscordLogo", component: DiscordLogoIcon},
  {name: "DividerHorizontal", component: DividerHorizontalIcon},
  {name: "DividerVertical", component: DividerVerticalIcon},
  {name: "Dot", component: DotIcon},
  {name: "DotFilled", component: DotFilledIcon},
  {name: "DotsHorizontal", component: DotsHorizontalIcon},
  {name: "DotsVertical", component: DotsVerticalIcon},
  {name: "DoubleArrowDown", component: DoubleArrowDownIcon},
  {name: "DoubleArrowLeft", component: DoubleArrowLeftIcon},
  {name: "DoubleArrowRight", component: DoubleArrowRightIcon},
  {name: "DoubleArrowUp", component: DoubleArrowUpIcon},
  {name: "Download", component: DownloadIcon},
  {name: "DragHandleDots1", component: DragHandleDots1Icon},
  {name: "DragHandleDots2", component: DragHandleDots2Icon},
  {name: "DragHandleHorizontal", component: DragHandleHorizontalIcon},
  {name: "DragHandleVertical", component: DragHandleVerticalIcon},
  {name: "DrawingPin", component: DrawingPinIcon},
  {name: "DrawingPinFilled", component: DrawingPinFilledIcon},
  {name: "DropdownMenu", component: DropdownMenuIcon},
  {name: "Enter", component: EnterIcon},
  {name: "EnterFullScreen", component: EnterFullScreenIcon},
  {name: "EnvelopeClosed", component: EnvelopeClosedIcon},
  {name: "EnvelopeOpen", component: EnvelopeOpenIcon},
  {name: "Eraser", component: EraserIcon},
  {name: "ExclamationTriangle", component: ExclamationTriangleIcon},
  {name: "Exit", component: ExitIcon},
  {name: "ExitFullScreen", component: ExitFullScreenIcon},
  {name: "ExternalLink", component: ExternalLinkIcon},
  {name: "EyeClosed", component: EyeClosedIcon},
  {name: "EyeNone", component: EyeNoneIcon},
  {name: "EyeOpen", component: EyeOpenIcon},
  {name: "Face", component: FaceIcon},
  {name: "FigmaLogo", component: FigmaLogoIcon},
  {name: "File", component: FileIcon},
  {name: "FileMinus", component: FileMinusIcon},
  {name: "FilePlus", component: FilePlusIcon},
  {name: "FileText", component: FileTextIcon},
  {name: "FontBold", component: FontBoldIcon},
  {name: "FontFamily", component: FontFamilyIcon},
  {name: "FontItalic", component: FontItalicIcon},
  {name: "FontRoman", component: FontRomanIcon},
  {name: "FontSize", component: FontSizeIcon},
  {name: "FontStyle", component: FontStyleIcon},
  {name: "Frame", component: FrameIcon},
  {name: "FramerLogo", component: FramerLogoIcon},
  {name: "Gear", component: GearIcon},
  {name: "GitHubLogo", component: GitHubLogoIcon},
  {name: "Globe", component: GlobeIcon},
  {name: "Grid", component: GridIcon},
  {name: "Group", component: GroupIcon},
  {name: "Half1", component: Half1Icon},
  {name: "Half2", component: Half2Icon},
  {name: "HamburgerMenu", component: HamburgerMenuIcon},
  {name: "Hand", component: HandIcon},
  {name: "Heading", component: HeadingIcon},
  {name: "Heart", component: HeartIcon},
  {name: "HeartFilled", component: HeartFilledIcon},
  {name: "Height", component: HeightIcon},
  {name: "HobbyKnife", component: HobbyKnifeIcon},
  {name: "Home", component: HomeIcon},
  {name: "IconJarLogo", component: IconJarLogoIcon},
  {name: "IdCard", component: IdCardIcon},
  {name: "Image", component: ImageIcon},
  {name: "InfoCircled", component: InfoCircledIcon},
  {name: "Input", component: InputIcon},
  {name: "InstagramLogo", component: InstagramLogoIcon},
  {name: "Keyboard", component: KeyboardIcon},
  {name: "LapTimer", component: LapTimerIcon},
  {name: "Laptop", component: LaptopIcon},
  {name: "Layers", component: LayersIcon},
  {name: "Layout", component: LayoutIcon},
  {name: "LetterCaseCapitalize", component: LetterCaseCapitalizeIcon},
  {name: "LetterCaseLowercase", component: LetterCaseLowercaseIcon},
  {name: "LetterCaseToggle", component: LetterCaseToggleIcon},
  {name: "LetterCaseUppercase", component: LetterCaseUppercaseIcon},
  {name: "LetterSpacing", component: LetterSpacingIcon},
  {name: "LightningBolt", component: LightningBoltIcon},
  {name: "LineHeight", component: LineHeightIcon},
  {name: "Link1", component: Link1Icon},
  {name: "Link2", component: Link2Icon},
  {name: "LinkBreak1", component: LinkBreak1Icon},
  {name: "LinkBreak2", component: LinkBreak2Icon},
  {name: "LinkNone1", component: LinkNone1Icon},
  {name: "LinkNone2", component: LinkNone2Icon},
  {name: "LinkedInLogo", component: LinkedInLogoIcon},
  {name: "ListBullet", component: ListBulletIcon},
  {name: "LockClosed", component: LockClosedIcon},
  {name: "LockOpen1", component: LockOpen1Icon},
  {name: "LockOpen2", component: LockOpen2Icon},
  {name: "Loop", component: LoopIcon},
  {name: "MagicWand", component: MagicWandIcon},
  {name: "MagnifyingGlass", component: MagnifyingGlassIcon},
  {name: "Margin", component: MarginIcon},
  {name: "MaskOff", component: MaskOffIcon},
  {name: "MaskOn", component: MaskOnIcon},
  {name: "Minus", component: MinusIcon},
  {name: "MinusCircled", component: MinusCircledIcon},
  {name: "Mix", component: MixIcon},
  {name: "MixerHorizontal", component: MixerHorizontalIcon},
  {name: "MixerVertical", component: MixerVerticalIcon},
  {name: "Mobile", component: MobileIcon},
  {name: "ModulzLogo", component: ModulzLogoIcon},
  {name: "Moon", component: MoonIcon},
  {name: "Move", component: MoveIcon},
  {name: "NotionLogo", component: NotionLogoIcon},
  {name: "Opacity", component: OpacityIcon},
  {name: "OpenInNewWindow", component: OpenInNewWindowIcon},
  {name: "Overline", component: OverlineIcon},
  {name: "Padding", component: PaddingIcon},
  {name: "PaperPlane", component: PaperPlaneIcon},
  {name: "Pause", component: PauseIcon},
  {name: "Pencil1", component: Pencil1Icon},
  {name: "Pencil2", component: Pencil2Icon},
  {name: "Person", component: PersonIcon},
  {name: "PieChart", component: PieChartIcon},
  {name: "Pilcrow", component: PilcrowIcon},
  {name: "PinBottom", component: PinBottomIcon},
  {name: "PinLeft", component: PinLeftIcon},
  {name: "PinRight", component: PinRightIcon},
  {name: "PinTop", component: PinTopIcon},
  {name: "Play", component: PlayIcon},
  {name: "Plus", component: PlusIcon},
  {name: "PlusCircled", component: PlusCircledIcon},
  {name: "QuestionMark", component: QuestionMarkIcon},
  {name: "QuestionMarkCircled", component: QuestionMarkCircledIcon},
  {name: "Quote", component: QuoteIcon},
  {name: "Radiobutton", component: RadiobuttonIcon},
  {name: "Reader", component: ReaderIcon},
  {name: "Reload", component: ReloadIcon},
  {name: "Reset", component: ResetIcon},
  {name: "Resume", component: ResumeIcon},
  {name: "Rocket", component: RocketIcon},
  {name: "RotateCounterClockwise", component: RotateCounterClockwiseIcon},
  {name: "RowSpacing", component: RowSpacingIcon},
  {name: "Rows", component: RowsIcon},
  {name: "RulerHorizontal", component: RulerHorizontalIcon},
  {name: "RulerSquare", component: RulerSquareIcon},
  {name: "Scissors", component: ScissorsIcon},
  {name: "Section", component: SectionIcon},
  {name: "SewingPin", component: SewingPinIcon},
  {name: "SewingPinFilled", component: SewingPinFilledIcon},
  {name: "Shadow", component: ShadowIcon},
  {name: "ShadowInner", component: ShadowInnerIcon},
  {name: "ShadowNone", component: ShadowNoneIcon},
  {name: "ShadowOuter", component: ShadowOuterIcon},
  {name: "Share1", component: Share1Icon},
  {name: "Share2", component: Share2Icon},
  {name: "Shuffle", component: ShuffleIcon},
  {name: "Size", component: SizeIcon},
  {name: "SketchLogo", component: SketchLogoIcon},
  {name: "Slash", component: SlashIcon},
  {name: "Slider", component: SliderIcon},
  {name: "SpaceBetweenHorizontally", component: SpaceBetweenHorizontallyIcon},
  {name: "SpaceBetweenVertically", component: SpaceBetweenVerticallyIcon},
  {name: "SpaceEvenlyHorizontally", component: SpaceEvenlyHorizontallyIcon},
  {name: "SpaceEvenlyVertically", component: SpaceEvenlyVerticallyIcon},
  {name: "SpeakerLoud", component: SpeakerLoudIcon},
  {name: "SpeakerModerate", component: SpeakerModerateIcon},
  {name: "SpeakerOff", component: SpeakerOffIcon},
  {name: "SpeakerQuiet", component: SpeakerQuietIcon},
  {name: "Square", component: SquareIcon},
  {name: "Stack", component: StackIcon},
  {name: "Star", component: StarIcon},
  {name: "StarFilled", component: StarFilledIcon},
  {name: "StitchesLogo", component: StitchesLogoIcon},
  {name: "Stop", component: StopIcon},
  {name: "Stopwatch", component: StopwatchIcon},
  {name: "StretchHorizontally", component: StretchHorizontallyIcon},
  {name: "StretchVertically", component: StretchVerticallyIcon},
  {name: "Strikethrough", component: StrikethroughIcon},
  {name: "Sun", component: SunIcon},
  {name: "Switch", component: SwitchIcon},
  {name: "Symbol", component: SymbolIcon},
  {name: "Table", component: TableIcon},
  {name: "Target", component: TargetIcon},
  {name: "Text", component: TextIcon},
  {name: "TextAlignBottom", component: TextAlignBottomIcon},
  {name: "TextAlignCenter", component: TextAlignCenterIcon},
  {name: "TextAlignJustify", component: TextAlignJustifyIcon},
  {name: "TextAlignLeft", component: TextAlignLeftIcon},
  {name: "TextAlignMiddle", component: TextAlignMiddleIcon},
  {name: "TextAlignRight", component: TextAlignRightIcon},
  {name: "TextAlignTop", component: TextAlignTopIcon},
  {name: "TextNone", component: TextNoneIcon},
  {name: "ThickArrowDown", component: ThickArrowDownIcon},
  {name: "ThickArrowLeft", component: ThickArrowLeftIcon},
  {name: "ThickArrowRight", component: ThickArrowRightIcon},
  {name: "ThickArrowUp", component: ThickArrowUpIcon},
  {name: "Timer", component: TimerIcon},
  {name: "Tokens", component: TokensIcon},
  {name: "TrackNext", component: TrackNextIcon},
  {name: "TrackPrevious", component: TrackPreviousIcon},
  {name: "Transform", component: TransformIcon},
  {name: "TransparencyGrid", component: TransparencyGridIcon},
  {name: "Trash", component: TrashIcon},
  {name: "TriangleDown", component: TriangleDownIcon},
  {name: "TriangleLeft", component: TriangleLeftIcon},
  {name: "TriangleRight", component: TriangleRightIcon},
  {name: "TriangleUp", component: TriangleUpIcon},
  {name: "TwitterLogo", component: TwitterLogoIcon},
  {name: "Underline", component: UnderlineIcon},
  {name: "Update", component: UpdateIcon},
  {name: "Upload", component: UploadIcon},
  {name: "Value", component: ValueIcon},
  {name: "ValueNone", component: ValueNoneIcon},
  {name: "VercelLogo", component: VercelLogoIcon},
  {name: "Video", component: VideoIcon},
  {name: "ViewGrid", component: ViewGridIcon},
  {name: "ViewHorizontal", component: ViewHorizontalIcon},
  {name: "ViewNone", component: ViewNoneIcon},
  {name: "ViewVertical", component: ViewVerticalIcon},
  {name: "Width", component: WidthIcon},
  {name: "ZoomIn", component: ZoomInIcon},
  {name: "ZoomOut", component: ZoomOutIcon},

  {name: "Bold", component: BoldIcon}, 
  {name: "Briefcase", component: BriefcaseIcon}, 
  {name: "Facebook", component: FacebookIcon}, 
  {name: "Italic", component: ItalicIcon},
  {name: "Pen", component: PenIcon}, 
  {name: "Trash2", component: Trash2Icon}, 
  {name: "AArrowUp", component: AArrowUpIcon}, 
  {name: "AArrowDown", component: AArrowDownIcon}, 
  {name: "ALargeSmall", component: ALargeSmallIcon},
  {name: "ArrowDownLeft", component: ArrowDownLeftIcon}, 
  {name: "ArrowDownRight", component: ArrowDownRightIcon}, 
  {name: "AlarmCheck", component: AlarmCheckIcon}, 
  {name: "AlarmClock", component: AlarmClockIcon},
  {name: "AlarmClockOff", component: AlarmClockOffIcon}, 
  {name: "AlarmPlus", component: AlarmPlusIcon}, 
  {name: "AlarmSmoke", component: AlarmSmokeIcon}, 
  {name: "MailWarning", component: MailWarningIcon},
  {name: "ArrowUpLeft", component: ArrowUpLeftIcon}, 
  {name: "ArrowUpRight", component: ArrowUpRightIcon}, 
  {name: "ArrowUpDown", component: ArrowUpDownIcon},
];

const iconsStyle = "w-7 h-7 cursor-pointer hover:bg-blue-600 rounded text-3xl";

export function Icons({addElementHandler}: {addElementHandler: (text: "text" | "image" | "icon", value: string) => void }) {
  const [input, setInput] = useState("");
  
  return (
    <>
      <h4 className="text-2xl text-center">Add icon</h4>
      <Input type="search" placeholder="search icon" onChange={v => setInput(v.target.value)} />
      <Label>select icon</Label>
      <Card className="my-2 h-96">
        <CardContent className="flex flex-row flex-wrap gap-2" style={{overflowY: "scroll", scrollbarWidth: "thin"}}>
          {icons.filter(i => i.name.toLocaleLowerCase().indexOf(input.toLocaleLowerCase())>-1).map(({name, component: Icon}, index) => (
            <div key={index} title={name} onClick={() => addElementHandler("icon", name)}>
              <Icon className={iconsStyle} />
            </div>
          ))}
        </CardContent>
      </Card>
    </>
  );
}


export function IconRenderer({ iconName, color, size, className }: { iconName: string, color: string | undefined, size: number | undefined, className: string | "" }) {
  const IconComponent = icons.filter(i => i.name === iconName)[0]?.component;
  if (!IconComponent) return <span></span>;
  return <IconComponent color={color? color : "#000"} className={className + ` w-${size} h-${size}`} />;
}
